library(MASS)
data(stackloss)
attach(stackloss)
outliers=c(1,3,4,21)
postscript("stackloss-points.ps")
par(mfrow=c(2,2))
plot(Air.Flow, stack.loss)
points(Air.Flow[outliers], stack.loss[outliers], col=(1:4)+1)
plot(Water.Temp, stack.loss)
points(Water.Temp[outliers], stack.loss[outliers], col=(1:4)+1)
plot(Acid.Conc., stack.loss)
points(Acid.Conc.[outliers], stack.loss[outliers], col=(1:4)+1)
plot(Air.Flow, stack.loss, type="n", axes=F,  ylab="", xlab="Legend")
legend(60,30, legend=as.character(outliers), pch=1,col=c(1:4)+1)
dev.off()

