markdown: kramdown
exclude:
  - LICENSE

layouts_dir: ./_noita
baseurl: /courses/Fall16/sta721

noita:
  name: Duke STA 721 - Linear Models (Fall 2016)
  description: Jekyll theme built with Foundation
  author:
    name: Merlise Clyde
    url: http://stat.duke.edu/~clyde
    absolute: true
  lang: en
  topbar:
    toggle: Menu
    right:
      - name: Info
        url: /
      - name: Syllabus
        url: /syllabus/
      - name: Calendar
        url: /calendar
      - name: Resources
        url: /resources/
      - name: Sakai
        url: https://sakai.duke.edu/x/xrqqk7
        absolute: true
      - name: Links
        url: /links/
social:
  github: merliseclyde
  linkedin: merliseclyde
